FROM openjdk:12
MAINTAINER Assel Amangeldi <lessam07@gmail.com>
ADD /target/user-details-0.0.1-SNAPSHOT.jar user-details-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "user-details-0.0.1-SNAPSHOT.jar"]

EXPOSE 8084