FROM openjdk:12
MAINTAINER Assel Amangeldi <lessam07@gmail.com>
ADD /target/discovery-server-0.0.1-SNAPSHOT.jar discovery-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "discovery-server-0.0.1-SNAPSHOT.jar"]

EXPOSE 8761