version: '2.2'
services:
    discovery-server:
        container_name: discovery-server
        build:
            context: ./discovery-server
        image: discovery-server:latest
        ports:
            - 8761:8761
