FROM openjdk:12
MAINTAINER Assel Amangeldi <lessam07@gmail.com>
ADD /target/zuul-server-0.0.1-SNAPSHOT.jar zuul-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "zuul-server-0.0.1-SNAPSHOT.jar"]

EXPOSE 8762