FROM openjdk:12
MAINTAINER Assel Amangeldi <lessam07@gmail.com>
ADD /target/order-history-0.0.1-SNAPSHOT.jar order-history-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "order-history-0.0.1-SNAPSHOT.jar"]

EXPOSE 8082