FROM openjdk:12
MAINTAINER Assel Amangeldi <lessam07@gmail.com>
ADD /target/payment-details-0.0.1-SNAPSHOT.jar payment-details-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "payment-details-0.0.1-SNAPSHOT.jar"]

EXPOSE 8083