FROM openjdk:12
MAINTAINER Assel Amangeldi <lessam07@gmail.com>
ADD /target/authentication-0.0.1-SNAPSHOT.jar authentication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "authentication-0.0.1-SNAPSHOT.jar"]

EXPOSE 9100